services:
  - type: web
    name: drone-bot
    env: python
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.8
